/** 占成代理 · 字段定义（与占成代理原型 UI 双向对齐） */

export type AgentFieldDefRow = {
  no: number | string
  name: string
  biz: string
  dimension: string
  method: string
  handler: string
}

export type AgentFieldDefModule = {
  id: string
  title: string
  rows: AgentFieldDefRow[]
}

export const AGENT_FIELD_DEF_META = {
  title: '字段定义',
  subtitle: '占成代理',
  source: 'Axure · v2.x.x-代理优化三期',
  columns: ['序号', '字段名', '业务口径', '统计维度', '统计方式', '处理方'] as const,
}

export const AGENT_FIELD_DEF_MODULES: AgentFieldDefModule[] = [
  {
    id: 'direct',
    title: '模块：【代理中心：我的直属】',
    rows: [
      {
        no: 1,
        name: '新增会员',
        biz: '我的直属会员在某个日期段新增数量',
        dimension: '汇总：我的直属会员+日期',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 2,
        name: '活跃人数',
        biz: '我的直属会员在某个日期段在线过',
        dimension: '汇总：我的直属会员+日期',
        method: '实时',
        handler: '金刚',
      },
      {
        no: 3,
        name: '充值总额',
        biz: '我的直属会员在某个日期段的某个币种充值总金额',
        dimension: '汇总：我的直属会员+日期+币种',
        method: '实时',
        handler: '金刚',
      },
      {
        no: 4,
        name: '取款总额',
        biz: '我的直属会员在某个日期段的某个币种取款总金额',
        dimension: '汇总：我的直属会员+日期+币种',
        method: '实时',
        handler: '金刚',
      },
      {
        no: 5,
        name: '有效投注',
        biz: '我的直属会员在某个日期段的某个币种有效投注总额',
        dimension: '汇总：我的直属会员+日期+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 6,
        name: '投注退水',
        biz: '我的直属会员在某个日期段的某个币种投注退水总额',
        dimension: '汇总：我的直属会员+日期+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 7,
        name: '优惠活动',
        biz: '我的直属会员在某个日期段的某个币种参加活动的获利总额',
        dimension: '汇总：我的直属会员+日期+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 8,
        name: 'VIP退水',
        biz: '我的直属会员在某个日期段的某个币种VIP退水总额',
        dimension: '汇总：我的直属会员+日期+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 9,
        name: 'VIP晋级礼金',
        biz: '我的直属会员在某个日期段的某个币种VIP晋级礼金总额',
        dimension: '汇总：我的直属会员+日期+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 10,
        name: 'VIP额外奖金',
        biz: '我的直属会员在某个日期段的某个币种VIP额外奖金总额',
        dimension: '汇总：我的直属会员+日期+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 11,
        name: '充提手续费',
        biz: '我的直属会员在某个日期段的某个币种充提手续费总额',
        dimension: '汇总：我的直属会员+日期+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 12,
        name: '游戏输赢',
        biz: '我的直属会员在某个日期段的某个币种游戏输赢总额',
        dimension: '汇总：我的直属会员+日期+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 13,
        name: '游戏净输赢',
        biz: '游戏净输赢 = 【游戏输赢】 + 【-退水】 + 【-VIP退水】 + 【-代理赚水】 + 【-场馆费】',
        dimension: '汇总：我的直属会员+日期+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 14,
        name: '净输赢',
        biz: '代理盈亏/净输赢 = 【游戏输赢】 + 【-退水】 + 【-VIP退水】 + 【-代理赚水】 + 【-场馆费】 + 【-VIP晋级礼金】 + 【-VIP额外奖金】 + 【-活动金】 + 【-充提手续费】',
        dimension: '汇总：我的直属会员+日期+币种',
        method: '10分钟',
        handler: '现金',
      },
    ],
  },
  {
    id: 'sub-agent',
    title: '模块：【代理中心：下级代理】',
    rows: [
      {
        no: 15,
        name: '新增会员',
        biz: '我的下级所有代理下的会员在某个日期段新增数量总额（不包含我的直属会员）',
        dimension: '汇总：我的下级所有代理下的会员+日期',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 16,
        name: '新增代理',
        biz: '我的下级所有级别的代理在某个日期段新增数量总额（包含直属代理）',
        dimension: '汇总：我的下级所有代理+日期',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 17,
        name: '活跃人数',
        biz: '我的下级所有代理下的会员在某个日期段的活跃人数（在线过）（不包含我的直属会员）',
        dimension: '汇总：我的下级所有代理下的会员+日期',
        method: '实时',
        handler: '金刚',
      },
      {
        no: 18,
        name: '团队代理',
        biz: '我的下级所有代理在某个日期段的截止日期人数的总和（包含直属代理）',
        dimension: '汇总：我的下级所有代理+截止日期',
        method: '实时',
        handler: '金刚',
      },
      {
        no: 19,
        name: '团队会员',
        biz: '我的下级所有代理下的会员在某个日期段的截止日期人数总和（不包含我的直属会员）',
        dimension: '汇总：我的下级所有代理下的会员+截止日期',
        method: '实时',
        handler: '金刚',
      },
      {
        no: 20,
        name: '投注（10人）',
        biz: '我的下级所有代理下的会员在某个日期段某个币种投注人数和投注总额（不包含我的直属会员）；原型展示「投注（人数）」',
        dimension: '汇总：我的下级所有代理下的会员+日期+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 21,
        name: '首存（10人）',
        biz: '我的下级所有代理下的会员在某个日期段某个币种首存人数和首存金额（不包含我的直属会员）；原型展示「首存（人数）」',
        dimension: '汇总：我的下级所有代理下的会员+日期+币种',
        method: '实时',
        handler: '金刚',
      },
      {
        no: 22,
        name: '充值（10人）',
        biz: '我的下级所有代理下的会员在某个日期段某个币种充值人数和充值金额总额（不包含我的直属会员）；原型展示「充值（人数）」',
        dimension: '汇总：我的下级所有代理下的会员+日期+币种',
        method: '实时',
        handler: '金刚',
      },
      {
        no: 23,
        name: '提款（10人）',
        biz: '我的下级所有代理下的会员在某个日期段某个币种提款人数和提款金额总额（不包含我的直属会员）；原型展示「提款（人数）」',
        dimension: '汇总：我的下级所有代理下的会员+日期+币种',
        method: '实时',
        handler: '金刚',
      },
      {
        no: 24,
        name: '优惠活动',
        biz: '我的下级所有代理下的会员在某个日期段某个币种参加活动的获利总额（不包含我的直属会员）',
        dimension: '汇总：我的下级所有代理下的会员+日期+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 25,
        name: '投注退水',
        biz: '我的下级所有代理下的会员在某个日期段某个币种投注退水总额（不包含我的直属会员）',
        dimension: '汇总：我的下级所有代理下的会员+日期+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 26,
        name: 'VIP退水',
        biz: '我的下级所有代理下的会员在某个日期段某个币种VIP退水总额（不包含我的直属会员）',
        dimension: '汇总：我的下级所有代理下的会员+日期+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 27,
        name: 'VIP晋级礼金',
        biz: '我的下级所有代理下的会员在某个日期段某个币种VIP晋级礼金总额（不包含我的直属会员）',
        dimension: '汇总：我的下级所有代理下的会员+日期+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 28,
        name: 'VIP额外奖金',
        biz: '我的下级所有代理下的会员在某个日期段某个币种VIP额外奖金总额（不包含我的直属会员）',
        dimension: '汇总：我的下级所有代理下的会员+日期+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 29,
        name: '充提手续费',
        biz: '我的下级所有代理下的会员在某个日期段某个币种充提手续费总额（不包含我的直属会员）',
        dimension: '汇总：我的下级所有代理下的会员+日期+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 30,
        name: '游戏输赢',
        biz: '我的下级所有代理下的会员在某个日期段某个币种游戏输赢总额（不包含我的直属会员）',
        dimension: '汇总：我的下级所有代理下的会员+日期+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 31,
        name: '游戏净输赢',
        biz: '游戏净输赢 = 【游戏输赢】 + 【-退水】 + 【-VIP退水】 + 【-代理赚水】 + 【-场馆费】（不包含我的直属会员）',
        dimension: '汇总：我的下级所有代理下的会员+日期+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 32,
        name: '净输赢',
        biz: '代理盈亏/净输赢 = 【游戏输赢】 + 【-退水】 + 【-VIP退水】 + 【-代理赚水】 + 【-场馆费】 + 【-VIP晋级礼金】 + 【-VIP额外奖金】 + 【-活动金】 + 【-充提手续费】（不包含我的直属会员）',
        dimension: '汇总：我的下级所有代理下的会员+日期+币种',
        method: '10分钟',
        handler: '现金',
      },
    ],
  },
  {
    id: 'report-game',
    title: '模块：【我的报表-游戏】',
    rows: [
      {
        no: 33,
        name: '充提手续费',
        biz: '该代理账号的直属会员充提手续费总额 + 该代理账号下所有代理的会员充提手续费总额',
        dimension: '汇总：（直属会员+非直属会员），日期，币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 34,
        name: '团队充值总额',
        biz: '该代理账号的直属会员充值总额 + 该代理账号下所有代理的会员充值总额',
        dimension: '汇总：（直属会员+非直属会员），日期，币种',
        method: '实时',
        handler: '金刚',
      },
      {
        no: 35,
        name: '团队提款总额',
        biz: '该代理账号的直属会员提款总额 + 该代理账号下所有代理的会员提款总额',
        dimension: '汇总：（直属会员+非直属会员），日期，币种',
        method: '实时',
        handler: '金刚',
      },
      {
        no: 36,
        name: '上下分净额',
        biz: '信用额度场景：会员上分总额 − 会员下分总额（代理团队口径）',
        dimension: '汇总：（直属会员+非直属会员），日期，币种',
        method: '实时',
        handler: '金刚',
      },
      {
        no: 37,
        name: '会员上分总额',
        biz: '信用额度场景：该代理账号下会员上分总额（含直属与下级代理下会员）',
        dimension: '汇总：（直属会员+非直属会员），日期，币种',
        method: '实时',
        handler: '金刚',
      },
      {
        no: 38,
        name: '会员下分总额',
        biz: '信用额度场景：该代理账号下会员下分总额（含直属与下级代理下会员）',
        dimension: '汇总：（直属会员+非直属会员），日期，币种',
        method: '实时',
        handler: '金刚',
      },
    ],
  },
  {
    id: 'report-pnl',
    title: '模块：【我的报表-盈亏】',
    rows: [
      {
        no: 39,
        name: '游戏净输赢',
        biz: '游戏净输赢 = 【实占游戏输赢】 + 【-实占退水】 + 【-实占VIP退水】 + 【-代理赚水】 + 【-场馆费】',
        dimension: '实占：（直属会员+非直属会员），日期，币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 40,
        name: '其他成本',
        biz: '其他成本 = 【-VIP晋级礼金】 + 【-VIP额外奖金】 + 【-活动金】 + 【-充提手续费】',
        dimension: '实占：（直属会员+非直属会员），日期，币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 41,
        name: '总盈亏',
        biz: '总盈亏 = 游戏净输赢 - 其他成本',
        dimension: '实占：（直属会员+非直属会员），日期，币种',
        method: '10分钟',
        handler: '现金',
      },
    ],
  },
  {
    id: 'agent-detail',
    title: '模块【代理详情】',
    rows: [
      {
        no: 42,
        name: '团队充值总额',
        biz: '该代理账号的所有下级会员充值总额，包含他的直属',
        dimension: '汇总：代理账号的直属会员+非直属会员+币种',
        method: '实时',
        handler: '金刚',
      },
      {
        no: 43,
        name: '团队提款总额',
        biz: '该代理账号的所有下级会员提款总额，包含他的直属',
        dimension: '汇总：代理账号的直属会员+非直属会员+币种',
        method: '实时',
        handler: '金刚',
      },
      {
        no: 44,
        name: '游戏净输赢',
        biz: '游戏净输赢 = 【实占游戏输赢】 + 【-实占退水】 + 【-实占VIP退水】 + 【-实占代理赚水】 + 【-场馆费】',
        dimension: '实占：代理账号的直属会员+非直属会员+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 45,
        name: '其他成本',
        biz: '其他成本 = 【-VIP晋级礼金】+【-VIP额外奖金】+【-活动金】+【-充提手续费】',
        dimension: '实占：代理账号的直属会员+非直属会员+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 46,
        name: '代理盈亏',
        biz: '代理盈亏 = 游戏净输赢-其他成本',
        dimension: '实占：代理账号的直属会员+非直属会员+币种',
        method: '10分钟',
        handler: '现金',
      },
    ],
  },
  {
    id: 'member-detail',
    title: '模块【会员详情】',
    rows: [
      {
        no: 47,
        name: '游戏净输赢',
        biz: '游戏净输赢 = 【游戏输赢】 + 【会员退水】 + 【VIP退水】（退水对会员为正）',
        dimension: '会员+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 48,
        name: '其他奖励',
        biz: '其他奖励 = VIP晋级礼金 + VIP额外奖金 + 活动金',
        dimension: '会员+币种',
        method: '10分钟',
        handler: '现金',
      },
      {
        no: 49,
        name: '会员盈亏',
        biz: '会员盈亏 = 游戏净输赢 + 其他奖励',
        dimension: '会员+币种',
        method: '10分钟',
        handler: '现金',
      },
    ],
  },
  {
    id: 'mine',
    title: '模块【我的】',
    rows: [
      {
        no: 50,
        name: '我的盈亏',
        biz: '代理团队币种盈亏',
        dimension: '实占：代理账号的直属会员+非直属会员+币种',
        method: '10分钟',
        handler: '现金',
      },
    ],
  },
]

export const AGENT_FIELD_DEF_FORMULAS = [
  '游戏净输赢（代理实占） = 【实占游戏输赢】 + 【-实占退水】 + 【-实占VIP退水】 + 【-代理赚水】 + 【-场馆费】',
  '代理盈亏/净输赢/总盈亏 = 游戏净输赢 - 其他成本；其他成本 = 【-VIP晋级礼金】 + 【-VIP额外奖金】 + 【-活动金】 + 【-充提手续费】',
  '会员盈亏 = 游戏输赢 + 会员退水 + VIP退水 + VIP晋级礼金 + VIP额外奖金 + 活动金（退水对会员为正）；亦等于 游戏净输赢 + 其他奖励；游戏净输赢 = 【游戏输赢】 + 【会员退水】 + 【VIP退水】；其他奖励 = VIP晋级礼金 + VIP额外奖金 + 活动金',
  '现金更新时间：10分钟左右',
]

export const AGENT_FIELD_DEF_SCENARIOS = [
  {
    title: '场景1：A1 创建A2代理,创建Au2会员',
    lines: [
      '代理A1->代理A2',
      '代理A1->直属会员A2',
      '代理A1->直属会员Au2',
      '统计：Au2 + A2',
    ],
  },
  {
    title: '场景2：B1，把Bu2挂到B1下面为二级代理',
    lines: ['代理B1->直属代理Bu2', '统计：0'],
  },
]
