/** 会话详情 · 多图消息静态资源（Figma 3390:116960） */
export const CHAT_ROOM_ASSETS = {
  avatar: '/images/chat-room/avatar.png',
  play: '/images/chat-room/play.svg',
  read: '/images/chat-room/icon-read.svg',
  add: '/images/chat-room/icon-add.svg',
  emoji: '/images/chat-room/icon-emoji.svg',
  mic: '/images/chat-room/icon-mic.svg',
  back: '/images/chat-room/icon-back.svg',
  more: '/images/chat-room/icon-more.svg',
  ai: '/images/chat-room/icon-ai.svg',
  videoCall: '/images/chat-room/icon-video.svg',
  phone: '/images/chat-room/icon-phone.svg',
  lock: '/images/chat-room/icon-lock.svg',
  plusWhite: '/images/chat-room/icon-plus-white.svg',
  reply: '/images/chat-room/icon-reply.svg',
  copy: '/images/chat-room/icon-copy.svg',
  forward: '/images/chat-room/icon-forward.svg',
  star: '/images/chat-room/icon-star.svg',
  trash: '/images/chat-room/icon-trash.svg',
  multi: '/images/chat-room/icon-multi.svg',
  pin: '/images/chat-room/icon-pin.svg',
  keyboard: '/images/chat-room/plus/keyboard.svg',
  plusActions: {
    photo: '/images/chat-room/plus/photo.svg',
    camera: '/images/chat-room/plus/camera.svg',
    transfer: '/images/chat-room/plus/transfer.svg',
    location: '/images/chat-room/plus/location.svg',
    gift: '/images/chat-room/plus/gift.svg',
    file: '/images/chat-room/plus/file.svg',
    contact: '/images/chat-room/plus/contact.svg',
    favorite: '/images/chat-room/plus/favorite.svg',
  },
  media: [
    '/images/chat-room/media-1.jpg',
    '/images/chat-room/media-2.png',
    '/images/chat-room/media-3.png',
    '/images/chat-room/media-4.jpg',
    '/images/chat-room/media-5.png',
  ],
} as const
